server:
  port: 5003
  
  
spring:
  application:
    name: SUBMISSION-SERVICE
    
  jpa:
    hibernate:
      ddl-auto: update
      
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/submission_service
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver